<template>
  <div>
    <div v-if="!isScanPage">
      <p>Please use your cold wallet client to scan this QR code. And click continue after your cold wallet client generates a QR code.</p>
      <div id="address-qrcode">
        <img :src="getQrCodeImg">
      </div>
      <b-row>
        <b-col class="col-lef">
          <b-button
            class="btn-back"
            block
            variant="light"
            size="lg"
            @click="prevPage">Back
          </b-button>
        </b-col>
        <b-col class="col-rit">
          <b-button
            block
            class="btn-confirm"
            variant="warning"
            size="lg"
            @click="nextPage">Continue
          </b-button>
        </b-col>
      </b-row>
    </div>
    <div v-if="isScanPage">
      <div class="qr-info">Show the QR code generated by your cold wallet client.</div>
      <div class="qr-window">
        <qrcode-reader @init="onInit"
                       @decode="onDecode"
                       :track="repaintLocation"
                       :paused="paused">
          <img v-if="qrInit"
               class="qrcode-waiting center"
               height="80"
               width="80"
               src="../../../assets/imgs/icons/wallet/ic_wait.svg">
        </qrcode-reader>
      </div>
      <p class="flink"
         v-if="qrError">
        Invalid signature. Please
        <b-button
          class="blink"
          @click="scanAgain"
          variant="link">
          scan again
        </b-button>
        .
      </p>
      <b-button variant="warning"
                class="btn-continue"
                size="lg"
                block
                :disabled="qrInit"
                @click="prevPage">Back
      </b-button>
    </div>
  </div>
</template>

<script>
import jrQrcode from 'jr-qrcode'
import transaction from '../../../utils/transaction'
export default {
    name: 'ColdSignature',
    data: function() {
        return {
            qrInit: false,
            paused: false,
            signature: '',
            scanShow: false,
            isScanPage: false,
            qrError: false
        }
    },
    props: {
        dataObject: {
            type: Object,
            require: true,
            default: function() {}
        }
    },
    computed: {
        getQrCodeImg() {
            const options = {
                padding: 10,
                width: 160,
                height: 160,
                correctLevel: 2,
                reverse: false,
                background: '#ffffff',
                foreground: '#000000'
            }
            const imgBase64 = jrQrcode.getQrBase64(JSON.stringify(this.dataObject), options)
            return imgBase64
        }
    },
    methods: {
        async onInit(promise) {
            try {
                this.qrInit = true
                this.qrError = false
                await promise
            } catch (error) {
                if (error.name === 'NotAllowedError') {
                    throw Error('user denied camera access permission')
                } else if (error.name === 'NotFoundError') {
                    throw Error('no suitable camera device installed')
                } else if (error.name === 'NotSupportedError') {
                    throw Error('page is not served over HTTPS (or localhost)')
                } else if (error.name === 'NotReadableError') {
                    throw Error('maybe camera is already in use')
                } else if (error.name === 'OverconstarinedError') {
                    throw Error('pass constraints do not match any camera')
                } else {
                    throw Error('browser is probably lacking features(WebRTC, Canvas)')
                }
            } finally {
                this.qrInit = false
            }
        },
        scanChange: function() {
            this.scanShow = !this.scanShow
        },
        onDecode: function(decodeString) {
            this.paused = true
            this.qrError = false
            try {
                var signature = JSON.parse(decodeString).signature
                if (!signature) {
                    this.paused = false
                } else {
                    var data = JSON.parse(JSON.stringify(this.dataObject))
                    delete data.transactionType
                    delete data.api
                    delete data.opc
                    delete data.protocol
                    data.timestamp *= 1e6
                    if (transaction.isValidSignature(data, signature, this.dataObject.senderPublicKey, this.dataObject.transactionType)) {
                        var _this = this
                        setTimeout(function() {
                            _this.$emit('get-signature', signature)
                        }, 300)
                    } else {
                        this.qrError = true
                    }
                }
            } catch (e) {
                this.qrError = true
            }
        },
        scanAgain: function() {
            this.paused = false
        },
        prevPage: function() {
            if (this.isScanPage) {
                this.isScanPage = false
            } else {
                this.$emit('prev-page')
            }
        },
        nextPage: function() {
            this.isScanPage = true
            this.paused = false
        },
        repaintLocation(location, ctx) {
            if (location !== null) {
                const {
                    topLeftCorner,
                    topRightCorner,
                    bottomLeftCorner,
                    bottomRightCorner
                } = location
                ctx.strokeStyle = 'orange' // instead of red
                ctx.beginPath()
                ctx.moveTo(topLeftCorner.x, topLeftCorner.y)
                ctx.lineTo(bottomLeftCorner.x, bottomLeftCorner.y)
                ctx.lineTo(bottomRightCorner.x, bottomRightCorner.y)
                ctx.lineTo(topRightCorner.x, topRightCorner.y)
                ctx.lineTo(topLeftCorner.x, topLeftCorner.y)
                ctx.closePath()
                ctx.stroke()
            }
        }
    }
}
</script>

<style scoped>
#address-qrcode {
    margin-top: 30px;
    text-align: center;
    margin-bottom: 40px;
}
.qrcode-waiting {
    vertical-align: middle;
    display: flex;
    margin-top: 10px;
    margin-right: auto;
    margin-left: auto;
    margin-bottom: 30px;
}
.qr-window {
    padding: 30px 100px;
}
.qr-info {
    text-align: center;
}
.btn-confirm {
    height: 44px;
    font-size: 17px;
    color: #FFFFFF;
    letter-spacing: 0;
    text-align: center;
}
.btn-back {
    background: #FAFAFA;
    border: 1px solid #E8E9ED;
    border-radius: 4px;
    font-size: 17px;
    color: #4F515E;
    letter-spacing: 0;
    text-align: center;
}
.col-lef {
    padding-right: 10px;
}
.col-rit {
    padding-left: 10px;
}
.blink {
    padding-top: 3px;
    padding-left: 0px;
    padding-right: 0px;
}
.flink {
    margin-top: 0px;
    margin-bottom: 20px;
}
.btn-continue {
    font-size: 17px;
    color: #FFFFFF;
    letter-spacing: 0;
    text-align: center;
    height: 50px;
}
</style>
